#!/usr/bin/env python3
"""生成可直接通过 file:// 打开的试听清单快照，不复制或改写音频。"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    repo = Path(__file__).resolve().parents[1]
    parser.add_argument(
        "--manifest", type=Path, default=repo / "assets/audio/audio_manifest.json"
    )
    parser.add_argument(
        "--output", type=Path, default=repo / "assets/audio/audition_data.js"
    )
    args = parser.parse_args()
    data = json.loads(args.manifest.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict) or not isinstance(data.get("assets"), list):
        raise ValueError("Manifest must be an object with an assets array")
    # 快照来自同一 manifest；页面无需 fetch 本地文件，也不会误用浏览器缓存。
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "// Generated by scripts/build_audition_index.py. Do not edit.\n"
        f"window.AUDIO_MANIFEST = {payload};\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Audition snapshot written: {args.output}")


if __name__ == "__main__":
    main()
